name: thesis_app_flutter
description: TheSiS App Flutter Version

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "TheSiS App"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_logo.png"

flutter:
  uses-material-design: true
